In [49]:
#This is an exploratory notebook which demonstrates some use of pandas, shapely, and the geocoder to work with polygon objects.

In [26]:
import googlemaps
import pandas
#from datetime import datetime
import shapely
import shapely.geometry as shp
from shapely.ops import nearest_points
import ast

In [48]:
APIkey = "Insert Your API key for the google geocoder"
#https://developers.google.com/maps/documentation/geocoding/start

In [6]:
gmaps = googlemaps.Client(key=APIkey)

In [7]:
##################################################
#POLYGONS
##################################################

In [5]:
poly = pandas.read_csv("data\\shiny_in\\parcel_zoning.csv")

In [7]:
poly = poly[["the_geom"]]

In [6]:
poly

,Unnamed: 0,the_geom,area,perimeter,basezone,overlay,znlabel,ordinance,update
0,0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",5.448490e+06,40159.850561,CIX-1,/S-19,CIX-1/S-19,12875,2011-03-15T07:00:00.000Z
1,1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",5.747361e+05,8355.138459,CIX-1,/S-19,CIX-1/S-19,12875,2011-03-15T07:00:00.000Z
2,2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",7.131569e+04,1532.053852,OS (NP),NaN,OS (NP),NaN,2011-03-15T07:00:00.000Z
3,3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",2.339572e+05,1975.040167,OS (NP),NaN,OS (NP),NaN,2011-03-15T07:00:00.000Z
4,4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",1.657815e+05,1726.611740,RM-1,NaN,RM-1,NaN,2011-03-15T07:00:00.000Z
...,...,...,...,...,...,...,...,...,...
995,995,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",2.274819e+05,2134.645993,RM-3,NaN,RM-3,NaN,2011-03-15T07:00:00.000Z
996,996,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",1.966043e+05,2081.612987,OS (NP),NaN,OS (NP),NaN,2011-03-15T07:00:00.000Z
997,997,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",1.976303e+06,10299.681899,RD-2,NaN,RD-2,NaN,2011-03-15T07:00:00.000Z
998,998,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",8.644390e+04,1226.140530,RU-5,NaN,RU-5,NaN,2011-03-15T07:00:00.000Z
999,999,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",7.472154e+05,4600.041866,CN-3,NaN,CN-3,NaN,2011-03-15T07:00:00.000Z

In [9]:
#evaluate string into python dictionary
x=eval(poly['the_geom'][0])

In [10]:
#convert dictionary to shapely multipolygon
x = shp.shape(x)

In [11]:
#compute centroid coordinates
coords = list(x.centroid.coords)

In [12]:
coords

[(-122.28773486025682, 37.816696283096256)]

In [13]:
def centroidCoords(shapeString):
    x=ast.literal_eval(shapeString)
    #flipped order to achieve standard format of (lat,lng) 
    flippedCoords = list(shp.shape(x).centroid.coords)[0]
    return (flippedCoords[1],flippedCoords[0])

In [14]:
cleaned = poly[poly.isna()["the_geom"]==False]

In [15]:
cleaned

                                              the_geom
0    {'type': 'MultiPolygon', 'coordinates': [[[[-1...
1    {'type': 'MultiPolygon', 'coordinates': [[[[-1...
2    {'type': 'MultiPolygon', 'coordinates': [[[[-1...
3    {'type': 'MultiPolygon', 'coordinates': [[[[-1...
4    {'type': 'MultiPolygon', 'coordinates': [[[[-1...
..                                                 ...
995  {'type': 'MultiPolygon', 'coordinates': [[[[-1...
996  {'type': 'MultiPolygon', 'coordinates': [[[[-1...
997  {'type': 'MultiPolygon', 'coordinates': [[[[-1...
998  {'type': 'MultiPolygon', 'coordinates': [[[[-1...
999  {'type': 'MultiPolygon', 'coordinates': [[[[-1...

[992 rows x 1 columns]

In [16]:
centroids = [centroidCoords(i) for i in cleaned['the_geom']]

In [17]:
cleaned["centroids"] = centroids
cleaned

C:\Users\Ryan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,the_geom,centroids
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.816696283096256, -122.28773486025682)"
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.80208929146703, -122.28331277567823)"
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.730031906229776, -122.1892493576412)"
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73135955903771, -122.13114716621865)"
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73163648892685, -122.1756897722274)"
...,...,...
995,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.77376245153254, -122.18438151183287)"
996,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.77267223723579, -122.18351320224113)"
997,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.77478371788555, -122.19328913026919)"
998,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.772327452024065, -122.19509591319331)"
999,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.77150077423684, -122.19121772971991)"

In [18]:
cleaned10 = cleaned[:10]

In [19]:
#input csv file path and name of column which contains the polygon data. 
def df_revgeocode(csv_path, col):
    poly = pandas.read_csv(csv_path)
    #only testing on first 10 rows to minimize api usage
    poly10 = poly[:10]
    poly10 = poly10[[col]]
    #remove rows without polygon data
    cleaned = poly10[poly10.isna()[col]==False]
    #compute centroid of each polygon
    centroids = [centroidCoords(i) for i in cleaned[col]]
    cleaned["centroids"] = centroids
    #reverse geocode to find matching addresses for centroid coordinates
    #some have multiple matching addresses for their coordinate => ouput as list
    cleaned["full_addrs"]=[gmaps.reverse_geocode(i,result_type="street_address") for i in cleaned["centroids"]]
    cleaned["formatted_addrs"] = [[j['formatted_address'] for j in i] for i in cleaned["full_addrs"]]
    return cleaned

In [20]:
x=df_revgeocode("data\\shiny_in\\parcel_zoning.csv", "the_geom")
x

,the_geom,centroids,full_addrs,formatted_addrs
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.816696283096256, -122.28773486025682)",[{'address_components': [{'long_name': '1300a'...,"[1300a W Grand Ave, Oakland, CA 94607, USA, 22..."
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.80208929146703, -122.28331277567823)","[{'address_components': [{'long_name': '499', ...","[499 Market St, Oakland, CA 94607, USA, 499 Ma..."
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.730031906229776, -122.1892493576412)","[{'address_components': [{'long_name': '9857',...","[9857 Hesket Rd, Oakland, CA 94603, USA, 9878 ..."
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73135955903771, -122.13114716621865)","[{'address_components': [{'long_name': '1698',...","[1698 Estudillo Ave, San Leandro, CA 94577, US..."
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73163648892685, -122.1756897722274)",[{'address_components': [{'long_name': '10922'...,"[10922 Edes Ave, Oakland, CA 94603, USA]"
5,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.728632868110694, -122.19612801416513)","[{'address_components': [{'long_name': '138', ...","[138 98th Ave, Oakland, CA 94603, USA, 148 98t..."
6,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73256809688579, -122.17864769339882)",[{'address_components': [{'long_name': '10501'...,"[10501 Acalanes Dr, Oakland, CA 94603, USA, 56..."
7,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73289345589321, -122.17121855804079)",[{'address_components': [{'long_name': '10962'...,"[10962 San Leandro St, Oakland, CA 94603, USA,..."
8,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.733147060679336, -122.17856208310226)","[{'address_components': [{'long_name': '591', ...","[591 105th Ave, Oakland, CA 94603, USA, 591 10..."
9,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...","(37.73444656254247, -122.13359807579121)","[{'address_components': [{'long_name': '3318',...","[3318 Revere Ave, Oakland, CA 94605, USA]"

In [21]:
x['centroids'][0]

(37.816696283096256, -122.28773486025682)

In [1]:
#addressstring -> geocoder -> lat/lon -> identify apn by matching coordinates with centroid

In [2]:
#########################

In [1]:
p = pandas.read_csv("../data/acgov/ac_gov_parcels.csv")

NameError: name 'pandas' is not defined

In [17]:
list(p)

['OBJECTID',
 'APN',
 'APN_SORT',
 'BOOK',
 'PAGE',
 'PARCEL',
 'SUB_PARCEL',
 'CLCA_CATEGORY',
 'COMMENTS',
 'DATE_CREATE',
 'DATE_UPDATE',
 'EDITOR',
 'FID_PARCELS',
 'CENTROID_X',
 'CENTROID_Y',
 'SortParcel',
 'PrintParcel',
 'TRAPrimary',
 'TRASecondary',
 'SitusStreetNumber',
 'SitusStreetName',
 'SitusUnit',
 'SitusCity',
 'SitusZip',
 'SitusZip_4',
 'Land',
 'Imps',
 'CLCALand',
 'CLCAImps',
 'HOEX',
 'OTEX',
 'TotalNetValue',
 'LatestDocument_Prefix',
 'LatestDocumentSeries',
 'LatestDocumentDate',
 'MailingAddressStreet',
 'MailingAddressUnit',
 'MailingAddressCityState',
 'MailingAddressZip',
 'MailingAddressZip_4',
 'UseCode',
 'EconUnit',
 'Units',
 'Class',
 'EffectiveYear',
 'BuildingArea',
 'LotSize',
 'Buildings',
 'Stories',
 'Rooms',
 'Beds',
 'Acre',
 'LandType',
 'Conformity',
 'Additions',
 'YearBuilt',
 'Baths',
 'Condo',
 'Elevator',
 'Pool',
 'EconomicUnit',
 'SitusAddress',
 'MailingAddress',
 'Shape__Area',
 'Shape__Length']

In [24]:
parcels=p[['APN', 'CENTROID_X', 'CENTROID_Y', 'SitusZip', 'SitusZip_4', 'UseCode', 'Class', 'LandType', 'YearBuilt', 'Shape__Area', 'Shape__Length']]

In [23]:
parcels

,APN,PARCEL,CENTROID_X,CENTROID_Y,SitusZip,SitusZip_4,UseCode,Class,LandType,YearBuilt,Shape__Area,Shape__Length
0,10-829-51,NaN,6.056096e+06,2.124923e+06,94610.0,NaN,7300.0,D7.0X,,1974.0,5026.863281,308.545412
1,10-829-52,NaN,6.056096e+06,2.124923e+06,94610.0,NaN,7300.0,D7.0X,,1974.0,5026.863281,308.545412
2,10-829-53,NaN,6.056096e+06,2.124923e+06,94610.0,NaN,7300.0,D7.0X,,1974.0,5026.863281,308.545412
3,10-829-54,NaN,6.056096e+06,2.124923e+06,94610.0,NaN,7300.0,D7.0X,,1974.0,5026.863281,308.545412
4,10-829-55,NaN,6.056096e+06,2.124923e+06,94610.0,NaN,7300.0,D7.0X,,1974.0,5026.863281,308.545412
...,...,...,...,...,...,...,...,...,...,...,...,...
482372,99B-5355-75,75,6.209132e+06,2.084590e+06,94551.0,NaN,1100.0,D7.5B,,2002.0,565.140625,99.902244
482373,99B-5355-74,74,6.209177e+06,2.084588e+06,94551.0,NaN,1100.0,D7.5B,,2002.0,586.390625,102.529993
482374,99B-5355-73,73,6.209222e+06,2.084584e+06,94551.0,NaN,1100.0,D7.5B,,2001.0,626.464844,106.554022
482375,99B-5355-72,72,6.209286e+06,2.084604e+06,94551.0,NaN,1100.0,D7.5B,,2002.0,618.789062,100.641199
482376,99B-5355-67,67,6.208624e+06,2.084592e+06,94551.0,NaN,1400.0,D7.5B,,2001.0,590.156250,113.476299

In [34]:
pts=[shp.Point(parcels["CENTROID_X"][i],parcels["CENTROID_Y"][i]) for i in range(len(parcels))]

In [47]:
print(pts[0])

POINT (6056095.85751141 2124922.6646201)

In [38]:
search = gmaps.geocode("973 86TH AVE, Oakland CA")
search[0]['formatted_address']

'973 86th Ave, Oakland, CA 94621, USA'

In [44]:
x=search[0]['geometry']['location']
x

{'lat': 37.7496222, 'lng': -122.1833853}

In [43]:
s = shp.Point(x['lat'])

{'lat': 37.7496222, 'lng': -122.1833853}